apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shows.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "shows.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "shows.name" . }}
    spec:
      containers:
        - name: {{ include "shows.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.springDatasourceUrl }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.env.springDatasourceUsername }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.env.springDatasourcePassword }}"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
