apiVersion: apps/v1
kind: Deployment
metadata:
  name: shows-deployment
  namespace: shows
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shows
  template:
    metadata:
      labels:
        app: shows
    spec:
      containers:
      - name: shows
        image: your-registry/shows:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: shows-secrets
              key: spring_datasource_url
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
